name: Fork News
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00
jobs:
  fork-news:
    runs-on: ubuntu-latest
    name: Syncing with parent repository
    steps:
      - id: fork-news-sync
        uses: vitornovictor/fork-news@v1.0.0
        with:
          access-token: ${{ secrets.FORK_NEWS_TOKEN }}

#TODO Add all the options with comments